CREATE TABLE Passports(
	PassportID INT PRIMARY KEY IDENTITY,
	PassportNumber VARCHAR(50)
)


CREATE TABLE Persons(
	PersonID INT PRIMARY KEY IDENTITY,
	FirstName VARCHAR(50) NOT NULL,
	Salary DECIMAL(10,2),
	PassportID INT FOREIGN KEY REFERENCES  Passports(PassportID)
)